// Mock data for testing without Google Sheets credentials
// Used automatically when GOOGLE_SHEET_ID is not set in .env

const guitars = [
  { id: 2,  rowIndex: 2,  submissionTime: '2024-01-10', name: 'תמר מעיין',     phone: '0507695341', city: 'רמת גן',    street: 'ביאליק 12',  email: 'tamar@example.com',   guitarType: 'קלאסית',  working: 'כן',   hasCase: 'לא',  defect: '', collected: true,  repaired: false, notes: 'גיטרה במצב טוב', whoRepairs: 'גיטר הלפ', model: 'Yamaha C40', donatedTo: 'עמותת עמיחי', region: 'מרכז', lat: 32.082, lon: 34.813 },
  { id: 3,  rowIndex: 3,  submissionTime: '2024-01-12', name: 'רבקה כהן',       phone: '0526979456', city: 'כרם מהר"ל', street: 'הגפן 3',    email: 'rivka@example.com',   guitarType: 'קלאסית',  working: 'לא',   hasCase: 'לא',  defect: 'מיתרים שבורים', collected: true,  repaired: true,  notes: 'דורשת טיפול', whoRepairs: 'אטדגי', model: 'Caraya', donatedTo: 'כפר הילדים', region: 'צפון', lat: 32.656, lon: 35.119 },
  { id: 4,  rowIndex: 4,  submissionTime: '2024-01-14', name: 'ניצן שגיא',      phone: '0542332853', city: 'יוקנעם',   street: 'התמר 7',    email: 'nitzan@example.com',  guitarType: 'קלאסית',  working: 'חצי',  hasCase: 'לא',  defect: 'לא נגע בה 10 שנים', collected: true,  repaired: false, notes: '',     whoRepairs: 'טל כפר ורדים', model: '', donatedTo: '', region: 'צפון', lat: 32.659, lon: 35.101 },
  { id: 5,  rowIndex: 5,  submissionTime: '2024-01-18', name: 'טל גולדשטיין',   phone: '0528891966', city: 'אלון אבא', street: '',          email: 'tal@example.com',     guitarType: 'קלאסית',  working: 'לא ברור', hasCase: 'לא', defect: '',  collected: true,  repaired: false, notes: '', whoRepairs: 'גיטר הלפ', model: '', donatedTo: 'עושים שכונה', region: 'צפון', lat: 32.7, lon: 35.15 },
  { id: 6,  rowIndex: 6,  submissionTime: '2024-01-20', name: 'אורלי דוידי',    phone: '0527434343', city: 'רמת גן',   street: 'ז\'בוטינסקי 45', email: 'orly@example.com', guitarType: 'אקוסטית', working: 'כן',   hasCase: 'כן',  defect: '',   collected: false, repaired: false, notes: '', whoRepairs: '', model: 'Fender', donatedTo: '', region: 'מרכז', lat: 32.069, lon: 34.823 },
  { id: 7,  rowIndex: 7,  submissionTime: '2024-02-01', name: 'יוסי לוי',       phone: '0541234567', city: 'חיפה',     street: 'הנמל 8',    email: 'yossi@example.com',   guitarType: 'חשמלית',  working: 'כן',   hasCase: 'כן',  defect: '',   collected: false, repaired: false, notes: 'גיטרה כמעט חדשה', whoRepairs: '', model: 'Ibanez', donatedTo: '', region: 'צפון', lat: 32.794, lon: 34.989 },
  { id: 8,  rowIndex: 8,  submissionTime: '2024-02-05', name: 'מיכל אברהם',     phone: '0509876543', city: 'תל אביב',  street: 'דיזנגוף 100', email: 'michal@example.com', guitarType: 'אקוסטית', working: 'כן',   hasCase: 'לא',  defect: '',   collected: true,  repaired: false, notes: '', whoRepairs: 'נועם', model: 'Yamaha', donatedTo: 'ווליום צפת', region: 'מרכז', lat: 32.081, lon: 34.774 },
  { id: 9,  rowIndex: 9,  submissionTime: '2024-02-10', name: 'דני שפירא',      phone: '0523456789', city: 'ירושלים',  street: 'יפו 55',    email: 'dani@example.com',    guitarType: 'קלאסית',  working: 'כן',   hasCase: 'כן',  defect: '',   collected: false, repaired: false, notes: '', whoRepairs: '', model: 'Kremona', donatedTo: '', region: 'ירושלים', lat: 31.778, lon: 35.216 },
  { id: 10, rowIndex: 10, submissionTime: '2024-02-15', name: 'שרה מזרחי',      phone: '0531234567', city: 'באר שבע',  street: 'רגר 4',     email: 'sara@example.com',    guitarType: 'אקוסטית', working: 'לא',   hasCase: 'לא',  defect: 'גוף שבור', collected: false, repaired: false, notes: '', whoRepairs: '', model: '', donatedTo: '', region: 'דרום', lat: 31.252, lon: 34.791 },
  { id: 11, rowIndex: 11, submissionTime: '2024-02-20', name: 'אבי נחום',       phone: '0548765432', city: 'נתניה',    street: 'הרצל 22',   email: 'avi@example.com',     guitarType: 'חשמלית',  working: 'כן',   hasCase: 'כן',  defect: '',   collected: true,  repaired: true,  notes: 'מצוינת', whoRepairs: 'הרצל', model: 'Gibson', donatedTo: 'אחים לחיים', region: 'שרון', lat: 32.333, lon: 34.857 },
  { id: 12, rowIndex: 12, submissionTime: '2024-03-01', name: 'רוני פרץ',       phone: '0526543210', city: 'אשדוד',    street: 'רוגוזין 8', email: 'roni@example.com',    guitarType: 'קלאסית',  working: 'חצי',  hasCase: 'לא',  defect: 'אוכף שבור', collected: false, repaired: false, notes: '', whoRepairs: '', model: '', donatedTo: '', region: 'דרום', lat: 31.804, lon: 34.655 },
  { id: 13, rowIndex: 13, submissionTime: '2024-03-05', name: 'לילך גרינברג',   phone: '0507654321', city: 'כפר ורדים', street: 'הדס 3',    email: 'lilach@example.com',  guitarType: 'אקוסטית', working: 'כן',   hasCase: 'כן',  defect: '',   collected: true,  repaired: false, notes: '', whoRepairs: 'טל כפר ורדים', model: 'Martin', donatedTo: 'חוות רימון', region: 'צפון', lat: 32.958, lon: 35.241 },
];

module.exports = { guitars };
